apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-pkcq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jccj-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-pkcq@sha256:ba9a177d516a8f1e773ebe6698bc92063397776be962f6db38abb8de92f9faec
        name: my-go
        resources: {}
status: {}
